version: '3.18'
services:
  auth:
    build: ./ds-auth/
    env_file:
      - ./ds-auth/.env
    ports: 
      - 4002:4002
    depends_on:
      - redis
  redis:
    image: redis:6.2.4
    ports:
      - 6379
  server:
    build: ./ds-webserver/
    env_file:
      - ./ds-webserver/.env
    ports:
      - 4000:4000
    depends_on:
      - auth
      - redis
  client:
    build: ./ds-client
    ports:
      - 3001:3001
    depends_on:
      - auth
      - server
  client_public:
    build: ./ds-client-public
    ports:
      - 3000:3000
    depends_on:
      - auth
      - server
  nginx:
    image: nginx:latest
    depends_on:
      - auth
      - server
      - client
      - client_public
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80